name: Build and Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Build and push backend
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctf-backend:latest

    - name: Build and push frontend
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        push: ${{ github.event_name == 'push' }}
        tags: ${{ secrets.DOCKER_HUB_USERNAME }}/ctf-frontend:latest

  deploy:
    needs: build
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
    - name: Install doctl
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Initialize connection to cluster
      run: doctl kubernetes cluster kubeconfig save ${{ secrets.CLUSTER_NAME }}

    - name: Deploy to Kubernetes
      run: |
        kubectl apply -f k8s/