name: Build and Push Docker Images

on:
  push:
    branches:
      - main  
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to DockerHub
      run: echo "$DOCKER_TOKEN" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build Backend Image
      run: |
        docker build -t $DOCKER_USERNAME/ctfplatform-backend ./backend
        docker push $DOCKER_USERNAME/ctfplatform-backend

    - name: Build Frontend Image
      run: |
        docker build -t $DOCKER_USERNAME/ctfplatform-frontend ./frontend
        docker push $DOCKER_USERNAME/ctfplatform-frontend
